name: CI

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write # Required for OIDC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm -w build
      - run: pnpm -r dev:prepare
      - run: pnpm -w typecheck
      - run: pnpm -r typecheck
      - run: pnpm lint
      - run: pnpm fmt:check
      - run: pnpm test:coverage
      - uses: codecov/codecov-action@v7
        with:
          use_oidc: true
          directory: coverage

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: pnpm build
      - name: Publish to npm
        run: pnpm publish --no-git-checks --provenance --tag latest
